require 'benchmark'
require 'health_monitor/monitors/health_monitor'
require 'health_monitor/monitors/simple_health_monitor'
require 'health_monitor/monitors/service_health_monitor'
require 'health_monitor/middleware/health_monitor_middleware'
require 'health_monitor/version'
